### ISSUE TITLE
Upgrade to 4.0.0

### ISSUE THREAD

**Issue by Y0ngg4n** [androidseb/flutter_map_floating_marker_titles#10]
flutter_maps 4.0.0 is released.
Please upgrade :)

**Comment by androidseb** [comment]
Nice! Exciting upgrade too, I'll look at this soon.

**Comment by androidseb** [comment]
And done, version 0.4.1 now uses flutter_map: ^4.0.0:
https://pub.dev/packages/flutter_map_floating_marker_titles/changelog

Enjoy :-)

**Comment by Y0ngg4n** [comment]
@androidseb thank you :)
