### ISSUE TITLE
onTap for titles

### ISSUE THREAD

**Issue by LondonJammo** [androidseb/flutter_map_floating_marker_titles#2]
When `flutter_map_floating_marker_titles` are used in conjunction with a `Marker()` in flutter_map, you get very good Markers with Labels. Using a `GestureDetector()` I've added an `onTap:()` event to the Marker, however I'd also like this available when tapping on the Label of the marker (your flutter_map_floating_marker_titles).

Are there any plans to add an onTap() event for this?

**Comment by androidseb** [comment]
Hey!

This is currently not in my plans, but it shouldn't be too difficult to implement yourself.

If you're interested I could give you some pointers about how to modify the code to achieve that?

**Comment by androidseb** [comment]
Closing this for now, feel free to re-open, if you want to continue that discussion, thanks!
