### ISSUE TITLE
Support for Apple Map

### ISSUE THREAD

**Issue by lfthwjx** [androidseb/flutter_map_floating_marker_titles#3]
It would be nicer if you could add support for Apple Map, there is a [package](https://pub.dev/packages/apple_maps_flutter) which is like Google Maps Flutter that could help if you plan to do that. Thanks a lot!

**Comment by androidseb** [comment]
Hey, thanks for bringing this up!

I don't see much value adding this just for one platform (iOS), so it's not something I would plan to do myself, but I'm not completely opposed to it, I could merge that in from a PR.

The whole library is agnostic of map view implementation, all you need to do is create a wrapper for the Apple maps view, see the Google map view implementation for reference, the code is pretty minimal:
https://github.com/androidseb/flutter_map_floating_marker_titles/blob/main/google_maps_flutter_floating_marker_titles/lib/google_maps_flutter_floating_marker_titles.dart

All you need is to implement 3 methods for the encapsulated map view's controller:
* getMapViewCenter
* getMapViewZoom
* getMapViewRotationDegrees

**Comment by androidseb** [comment]
There hasn't been any activity here for a while, I'll close this, feel free to re-open if you have a PR for this, thanks!
