### ISSUE TITLE
Zoom always centre screen, not offset

### ISSUE THREAD

**Issue by LondonJammo** [androidseb/flutter_map_floating_marker_titles#4]
hi Seb,

When I zoom, the map zooms always into the centre of the map, and not the centre of the gesture, which may be off to one side.

Is there an option I have missed, or can be set, to do this?

Cheers

**Comment by androidseb** [comment]
Hey, are you seeing this behavior in general in flutter_map, or specifically when using [flutter_map_floating_marker_titles](https://github.com/androidseb/flutter_map_floating_marker_titles)? The behavior you're describing seems to be specific to flutter_map.
