### ISSUE TITLE
FLUTTER_MAP: Bump version to v1.0.0

### ISSUE THREAD

**Issue by JaffaKetchup** [androidseb/flutter_map_floating_marker_titles#6]
Hi there,

'flutter_map' v1.0.0 has just been released with a few breaking changes but many new features, fixes, and performance improvements. Please consider updating your plugin to make it more accessible to users!

If you want to join the new Discord server, either just because, or because you want to offer more support to your users, just join using the link on the README. Please ping me and I'll give you the plugin maintainer role and access to a plugin support channel :)

Many thanks,
'flutter_map' maintainer (Luka S)

**Comment by androidseb** [comment]
Nice, thanks for letting me know!

I'll definitely want to upgrade to the latest version of flutter_map, I'll work on that soon, most likely within the next month.

I'll leave this issue open in the meantime.

**Comment by androidseb** [comment]
This is now done!

I updated the library to version 0.0.6, and it's now using flutter_map 1.0.0:

https://pub.dev/packages/flutter_map_floating_marker_titles/changelog

I'll close this issue now.
