### ISSUE TITLE
Could you please update dependencies of flutter_map to latest version 2.2.0

### ISSUE THREAD

**Issue by sirik-ck** [androidseb/flutter_map_floating_marker_titles#7]
Hello,

'flutter_map' have latest version 2.2.0.
Could you please update your library to support it?

Thank you for your great library.

Best regards,
Sirik.

**Comment by androidseb** [comment]
Hey, thanks for bringing this up.
This is now done:
https://pub.dev/packages/flutter_map_floating_marker_titles

Enjoy!
